### ISSUE TITLE
Hidden Fields dürfen bearbeitbar sein

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/moodle-qtype_questionpy#141]
Bislang ist es so, dass die Hidden Fields (in den Options als auch Question UI) sich bei uns anders als die restlichen Felder verhalten. Im Zusammenhang mit JavaScript spielen die Felder allerdings potentiell eine wichtige Rolle, um Informationen speichern zu können, die nicht über normale Formularfelder eingegeben werden.

* In den Options wird der Wert auf den vom Paket festgelegten Wert fixiert.
  * Gab es hier eine wichtige Überlegung, warum man das brauchen könnte?
  * Im Zusammenhang mit https://github.com/questionpy-org/questionpy-sdk/issues/140 könnte ein fixer Wert zwar prinzipiell sinnvoll sein, aber andererseits müssen wir auch nicht unbedingt den Fall abfangen, dass ein Trainer über die Web Developer Tools versteckte Felder bearbeitet.
* Im UI Renderer wird der zuletzt gespeicherte Wert nicht wieder geladen https://github.com/questionpy-org/moodle-qtype_questionpy/blob/513fedc39effccbe3b4b2697728668691a1c6b3a/classes/question_ui_renderer.php#L307-L308

**Comment by MHajoha** [comment]
> Gab es hier eine wichtige Überlegung, warum man das brauchen könnte?

Ich glaube nicht. 

Was den Rest der Zeile (`$type != "button" && $type != "submit"`) betrifft: Wollen wir dort auch das Ändern der Value aus JS erlauben? Ich sehe da keinen Use-Case für, aber auch keine Gegenargumente

**Comment by MartinGauk** [comment]
Ja, dann erlauben wir das auch an der Stelle.
