### ISSUE TITLE
Defaults überschreiben gespeicherte Werte

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/moodle-qtype_questionpy#44]
Wenn das Paket in den Optionen default values definiert, werden die vom Plugin beim Bearbeiten einer bestehenden Frage immer angezeigt statt des gespeicherten Wertes. 

Ich habe festgestellt, dass das mit `\HTML_QuickForm_element::onQuickFormEvent` zusammenhängt und dem Aufruf `$this->_findValue($caller->_defaultValues);`
Unser `$context->set_default` setzt den Wert unter dem Element-Namen `qpy_form[x][y]`. `set_data` setzt aber verschachtelte arrays und `_findValue` sucht zuerst nach `qpy_form[x][y]`.

**Comment by MHajoha** [comment]
Den Bug habe ich mit #43 eingebaut und jetzt auch darin gefixt
