### ISSUE TITLE
Endpoint zum Suchen nach Paketen

### ISSUE THREAD

**Issue by MartinGauk** [questionpy-org/moodle-qtype_questionpy#68]
### Endpoint
Entwerfe bitte auf Grundlage unserer UI-Überlegungen im Mai, welche Argumente und welche Rückgabewerte ein Ajax-Endpoint zum Suchen nach Paketen im Backend haben sollte und implementiere diese. Der Endpoint sollte die Ergebnisse paginiert zurückgeben. Bitte dokumentiere in diesem Issue zunächst die exakten Argumente/Rückgabewerte.

### DB-Abfragen effizienter machen
Aktuell sind die DB-Abfragen (zum Holen der Paketinformationen) nicht effizient, d.h. es werden zu viele Abfragen in Schleifen gestellt. Bitte nutze JOINs bzw. sammle IDs und hole die Infos gebündelt.

**Comment by janbritz** [comment]
### Endpoint
##### Argumente
```
query: string = "" - Suchtext
tags: list[int] = [] - Tag-IDs
category: string = "all" | "recentlyused" | "favourites" | "mine" - Art der zu durchsuchenden Pakete
sort: string = "alpha" | "date" - Sortierfunktion ("alpha" -> alphabetisch, "date" -> zuletzt hinzugefügt)
order: string = "asc" | "desc" - Auf- oder absteigende Sortierung

limit: int = 10 - Seitengröße (maximale Paketanzahl)
page: int  = 0 - Seite

contextid: int - Eine Kontext-ID
```

##### Rückgabewerte
```
packages: list[package] - Liste der Pakete auf der aktuellen Seite
count: int - Anzahl der Pakete auf der aktuellen Seite
total: int - Anzahl aller qualifizierten Pakete
```

###### package
```
id: int
shortname: string
namespace: string
versions: list[version]
author: string
name: string
url: ?string
description: ?string
icon: ?string
license: ?string
tags: list[tag]
isfavourite: bool
```

###### version
```
id: int
hash: string
version: string
ismine: bool
```

###### tag
```
id: int
tag: string
```

**Comment by janbritz** [comment]
Ansätze:

1. Im aktuellen Ansatz werden nur die Pakete eines bestimmten Tabs gefetcht (z.B. beim Wechsel eines noch nicht geöffneten Tabs) und die Paketanzahl der in `get_total` angegebenen `category`s.
2. Im vorherigen Ansatz musste für jede `category` ein Request erstellt werden, die allerdings über die Moodle Web Service API zu einem einzigen HTTP-Request gebündelt werden können. Das ist eine einfache und flexible, jedoch nicht die effizienteste Lösung, da dadurch alle Pakete jeder `category` gefetcht werden würden.

Zu 2.: Der Nutzer hätte keinen Delay beim Wechseln des Tabs, da die Pakete schon gefetched wurden - bei kleiner Seitengröße ist der initiale Delay vermutlich vertretbar, allerdings möchte der Nutzer vielleicht gar nicht den Tab wechseln, wodurch dieser unnötig länger warten muss.

**Comment by MartinGauk** [comment]
Das klingt sinnvoll. Ich denke, dass der Ansatz 2 verfolgt werden sollte.

Zu den Rückgabewerten: next/prev/self sind nicht notwendig, denke ich, da es ja als Argument `offset` gibt. Ich fürchte diese Links ließen sich in Moodle auch nicht erzeugen, da die Endpoints nicht nur per Ajax, sondern auch über Rest/SOAP/etc.-Schnittstellen aufrufbar sind.

Was meinst du mit "tags: list[str] - Zunächst nur Strings"?

Die Kategorie "recent" sollte genauer bezeichnet werden, "recentlyused"?

Denke an die merkwürdige Moodle-Konvention, dass in den Attributs-/Variablennamen keine Unterstriche erlaubt sind.

**Comment by janbritz** [comment]
Ursprünglich waren Ansatz 1 und 2 vertauscht, deshalb möchte ich nochmal sicher gehen, ob du wirklich Ansatz 2 meinst. Die jetztige Beschreibung der Argumente und Rückgabewerte bezieht sich auf Ansatz 1.

Alles klar! Ich hatte bis jetzt auch nichts gefunden, womit man next/prev einfach/überhaupt umsetzen kann.

Ich habe meinen Kommentar enfernt - der sollte da nicht mehr sein.

**Comment by MartinGauk** [comment]
Ansatz 2 wie er aktuell oben steht, meine ich. Ich glaube das macht den Endpoint sauberer und gleichzeitig wird die Seite zum Fragen Erstellen/Bearbeiten ja nicht ständig aufgerufen.

**Comment by MartinGauk** [comment]
Noch kleinere Anmerkungen:

- Da Moodle aus Australien kommt, soll man bevorzugt britisches Englisch verwenden. Schreibe daher bitte "favourite".
- Als Argument sollten wir die tags in Form von IDs annehmen. In der package Struktur sollten die Tag-ID und den string zurückgegeben werden. Die IDs machen es später einfacher, wenn wir Tags übersetzen wollen.
- Vermutlich brauchen wir auch einen Endpoint, der alle verfügbaren Tags zurückgibt.
