### ISSUE TITLE
Upload Form for QPy packages

### ISSUE THREAD

**Issue by alexanderschmitz** [questionpy-org/moodle-qtype_questionpy#7]
Von der Question Edit Form wollen wir auf eine neue Seite gelangen für den QPy package Upload.
Die Form sollte enthalten:

- Filepicker feld
- Felder für den Namen des Pakets, Author, Beschreibung, etc.

**Comment by MartinGauk** [comment]
Ich glaube, dass sogar nur das Filepicker Feld schon ausreicht. Name, usw. sind ja in den Metadaten des Pakets bereits enthalten.

Auf der Seite mit dem Upload-Formular sollten auch die im Kurs bereits hochgeladenen Pakete aufgelistet werden.
